### ISSUE TITLE
How can we use this in Blade

### ISSUE THREAD

**Issue by andreaskviby** [rmunate/AgentDetection#4]
You should make all of this also as Blade Directives

**Comment by rmunate** [comment]
@andreaskviby

Hello, could you create a helper to use functions in the views, in the same way I will be working on very simple to use Blade directives similar to the following
```php
@agentMobile
   // ...
@endAgentMobile
```

**Comment by andreaskviby** [comment]
Wow that would be awesome

**Comment by rmunate** [comment]
@andreaskviby In response to your request, version 1.2.0 has been released, I appreciate the reviews, your comments, contributions and support are useful to me.

https://github.com/rmunate/AgentDetection/releases/tag/v1.2.0
